#Data Time in Python

import datetime as dt

current_date=dt.date.today()
print("current Date : ",current_date)
print("=====")
new =dt.date(2004,3,13)
print(new)
print(new.year)
print(new.month)
print(new.day)
print("=====")
a=dt.time(10,45,5,55555)
print(a)
print(a.hour)
print(a.minute)
print(a.second)
print(a.microsecond)
print("====")
current_time=dt.datetime.now()
print(current_time )
print("=====")
new=dt.datetime(2004,3,13,11,35,10)
print(new)
print(new.date())
print(new.time())
print("=====")
current=dt.datetime.now()
new_year=dt.datetime(2004,3,13)
difference=new_year - current
print(difference)
print("=====")
current=dt.datetime.now()
print(current)
print("=====")
a=current.strftime("%A %B %D %Y")
print(a)

